### ISSUE TITLE
missing 1 required positional argument: 'num_classes' in 'from_pretrained'

### ISSUE THREAD

**Issue by desireevl** [huggingface/pytorch-transformers#833]
I am running a [multiclass BERT classification](https://github.com/desireevl/Bert-Multi-Label-Text-Classification/blob/master/train_bert_multi_label.py) model and am receiving the following error:

`
Traceback (most recent call last):
  File "train_bert_multi_label.py", line 144, in <module>
    main()
  File "train_bert_multi_label.py", line 78, in main
    num_classes = len(id2label))
  File "/opt/miniconda3/envs/tempenv/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 403, in from_pretrained
    model = cls(config)
TypeError: __init__() missing 1 required positional argument: 'num_classes'
`

The script worked fine when using `pytorch-pretrained-bert` and am guessing there is an issue from the new release. 

Thanks for the great tools :)

**Comment by thomwolf** [comment]
Yes, @xanlsh is working on an update to reduce the effect of this breaking change in #866.

You should be able to keep your script unchanged.

**Comment by xanlsh** [comment]
@desireevl Since #866 has been merged, your code should work now

**Comment by desireevl** [comment]
Thanks!
